name: ModelScope Keep Alive
on:
  schedule:
    - cron: '30 16 * * *' # 北京时间 00:30 (任务前 30 分钟)
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Space
        run: |
          curl -I https://你的用户名-空间名.modelscope.space/ || echo "Ping OK"
